### PR TITLE
Main.qml: Capitalize Insufficient funds message

### PR DESCRIPTION
**Pull request by xmr-eric**

### CODE REVIEW

**Comment by Jaqueeee** [comment]
Not sure if it's a good idea to merge these kind of small typo fixes before the release, since they could invalidate the translations (needs to be tested). It could be worked around by updating the source string in the translations files at the same time. @xmr-eric @rpcjacobs

**Comment by fluffypony** [comment]
Plz squash commits, don't need to have them all in separate commits:)

**Comment by xmr-eric** [comment]
@fluffypony How do I do that? I've only used Github.com via my browser to edit the repository. Do I have to download software?

**Comment by xmr-eric** [comment]
Figured it out :)

**Pull request merged**
