### PR TITLE
AddressBook

### PR DESCRIPTION
**Pull request by Jaqueeee**
Requires https://github.com/monero-project/monero/pull/1434

### CODE REVIEW

**Comment by taushet** [comment]
I'll test this on win/linux once monero-project/monero#1434 is merged (looks like there was some discussion about the key system used on that PR).

**Comment by Jaqueeee** [comment]
#1434 merged. Ping @taushet @xmr-eric @medusadigital

**Comment by taushet** [comment]
Dragged away from home with work over the next few days, can't build on a chromebook, no testing from me :(

**Comment by xmr-eric** [comment]
Mousing over the Description in a saved entry makes the address disappear (actually it slides really far to the right, only looks like it is disappearing. 

OSX 10.12.1

**Comment by xmr-eric** [comment]
addressbook

**Comment by fluffypony** [comment]
Comments above, and please also rebase

**Comment by medusadigital** [comment]
@xmr-eric  thats basically "works as designed"  and a featrue in my view.

the only thing i imagine we could do is go by description length. if its <10 character we dont push it to the right. 

doesnt seem worth the effort to me. 

should be merged like it is (after rebase)

**Comment by Jaqueeee** [comment]
Rebased. 
Yes. worked as designed. We could change it future but imo its OK like this.

**Comment by xmr-eric** [comment]
Perhaps push the address not as far, so people can still see the first 5-10 characters.

**Comment by medusadigital** [comment]
we do have an artefact on Ubuntu. Windows and OSX seem not affected by this. 


adress_tooltip

**Pull request merged**
