### PR TITLE
Change OrganizationName to MoneroProject

### PR DESCRIPTION
**Pull request by hyc**
Get rid of spaces, makes for ugly .config path on POSIX systems
Obsoletes #96

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
Wouldn't "Monero" be a more elegant solution?

**Comment by maitscha** [comment]
+1 for "Monero"

**Comment by hyc** [comment]
I used "MoneroProject" since the github org name is also "monero-project" and this was close enough without using special characters.

**Comment by taushet** [comment]
+1 'Monero'.

**Comment by xmr-eric** [comment]
+1 Monero

**Comment by moneromooo-monero** [comment]
I kinda like Monero better, but since this is a directory, it'll possibly end up having a kovri.conf file in it too at some point, and MoneroProject might make more sense in that light.

**Comment by hyc** [comment]
@moneromooo-monero exactly. This is an organization name and it shouldn't be so specific since the Monero Project has other software, not just Monero itself.

**Comment by fluffypony** [comment]
+1 for @hyc's suggestion. I've given up wanting lowercase folders on everything, and have grown to accept the occasional title-cased folder name:)

**Comment by peronero** [comment]
If the idea is that the .config directory serves as an umbrella "vendor" location for Monero Project projects, and the reasoning behind 'MoneroProject' is to maintain consistency with Github, then isn't 'monero-project' a better solution? Is Qt's Organization Name exposed to end-users anywhere?

**Comment by moneromooo-monero** [comment]
You know what ? We totally should bypass Qt's silly system and write to ~/.monerorc like any sane software.

**Comment by fluffypony** [comment]
Can we get some consensus and figure out how to move forward with this? Thanks:)

**Comment by hyc** [comment]
At this point all I really care is
* no embedded spaces
* the name should reflect the Project, not just "monero"

monero-project is fine with me.

**Comment by Jaqueeee** [comment]
monero-project is ok.

**Comment by moneromooo-monero** [comment]
Seems fine to me.

**Comment by hyc** [comment]
obsoleted by #267

**Pull request closed without merging**
