### PR TITLE
Change project name to Monero

### PR DESCRIPTION
**Pull request by Jaqueeee**
Fixes https://github.com/monero-project/monero-core/issues/60

### CODE REVIEW

**Comment by fluffypony** [comment]
I'm confused about this - organisation name *should* be the Monero Project, and the application is Monero Core. Does this appear somewhere that's making it confusing?

**Comment by Jaqueeee** [comment]
OK. I'm not sure if it appears in any other places except config dir mentioned in https://github.com/monero-project/monero-core/issues/60
Let me see if i can find any alternative ways of setting that dir name without changing the organization name.

**Comment by Jaqueeee** [comment]
Ok. It seems there's no other trivial ways of changing that config folder name. So it's up to you @fluffypony if you wan't to close this and continue using "The Monero Project" as folder name.

**Comment by fluffypony** [comment]
Let's close this for now, it could come in handy later on (having a The Monero Project folder I mean)

**Comment by moneromooo-monero** [comment]
Looking into this, it seems it's Qt being silly.
The "organization" name is to organize config based on who wrote the program, so it'll write ~/.config/organization/program.conf. So orgnization doesn't actually mean author (though they use company names in their examples). Normally you'd have ~/.config/program/X with X being whatever file(s) you use there, but they seem to have this hardcoded to use the above.

**Comment by peronero** [comment]
Updated originating ticket:

https://github.com/monero-project/monero-core/issues/60#issuecomment-258996349

**Comment by Jaqueeee** [comment]
@fluffypony Please reconsider this one.  See https://github.com/monero-project/monero-core/pull/96

**Pull request closed without merging**
