### PR TITLE
Enable translations

### PR DESCRIPTION
**Pull request by Jaqueeee**

### CODE REVIEW

**Comment by NanoAkron** [comment]
No Bahasa Indonesia?

**Comment by Jaqueeee** [comment]
@NanoAkron I've only enabled those who were previously disabled. Indonesia needs a flag (lang/flags/indonesia.png) before it can be added.

**Comment by fluffypony** [comment]
Ah missed the conflict - @Jaqueeee please rebase

**Comment by NanoAkron** [comment]
Here's one:

http://img.freeflagicons.com/thumb/round_icon/indonesia/indonesia_640.png

**Pull request merged**
