### PR TITLE
settings: replace seed box with popup

### LINKED ISSUE #445: [User Interface] Settings page doesn't scale properly when using default resolution
Using default resolution the bottom strings seem to fall off the page, see screenshot:

https://i.imgur.com/HfKPfEC.png

### PR DESCRIPTION
**Pull request by Jaqueeee**
Fixes #445

### CODE REVIEW

**Comment by xmr-eric** [comment]
The password prompt remains open even after the seed box popup is closed.

**Comment by fluffypony** [comment]
@Jaqueeee ^^

**Comment by Jaqueeee** [comment]
@xmr-eric can not reproduce. Platform?

**Comment by xmr-eric** [comment]
@Jaqueeee OSX 10.12.3. If I click on the Show Seed button, it asks me for my password. If I enter the correct password it shows the seed box. If I click OK to close the box, the password prompt box is still open.

**Comment by Jaqueeee** [comment]
@xmr-eric weird. Can't reproduce on osx 10.11.6. I suggest we merge this anyway to get more input from other users @fluffypony.

**Pull request merged**
