### PR TITLE
Fix issues related to spaces in path

### LINKED ISSUE #642: monerod.exe failed to load ver win64
Good Evening Everyone,

I was told to come here to add an issue that I encountered within the win 64bit version of Beta 2. When you load the GUI application it says it is starting demon then will fail with the statement "Please check your wallet and daemon log for errors. You can also try to start monerod.exe manually.". 

After i click OK on the failed start message, the bottom left status message will say "Connected" and the process monerod.exe will be running within the Task Manager.  

When I go to the settings tab it will show that the daemon is not running. The "Start daemon" is bold and the "Stop daemon" is grey'd out.
[bitmonero.zip](https://github.com/monero-project/monero-core/files/880573/bitmonero.zip)

### PR DESCRIPTION
**Pull request by Jaqueeee**
Fixes #642. Hopefully also #644

### CODE REVIEW

**Comment by xmr-eric** [comment]
My issue seems fixed by this. I renamed my `monero-wallet-gui` file to `monero-wallet-gui beta2` and it did not error like last time.

**Comment by danrmiller** [comment]
How does the translations/monero-core_da.ts file relate to this PR?

**Comment by RMLEARNEY** [comment]
@danrmiller good point

**Comment by Jaqueeee** [comment]
removed translation file added by mistake

**Comment by 2SI3NX** [comment]
**This issue still exists for Ubuntu 16.04.**

I run start-gui.sh, it opens up the GUI, tries to start up the daemon from GUI but it starts it up in the background, GUI shows popup that it cannot be started and persists that way, however - i see in the log that network is synchronizing and daemon is running correctly but GUI daemon status is not valid.

The above only happens when i run start-gui.sh from something like:
/home/user/Pictures/new folder with spaces/monero-gui-0.10.3.1-beta2/start-gui.sh

If i run it from a path like:
/home/user/Pictures/monero-gui-0.10.3.1-beta2/start-gui.sh

then there is no problem and the GUI recognizes that the daemon is active and running.

**Comment by Jaqueeee** [comment]
@2SI3NX is this when using Beta 2? This PR wasn't merged when beta 2 was built. Next release will have this fix.

**Comment by 2SI3NX** [comment]
yes @Jaqueeee . ok thanks just thought id let you know.

**Comment by Jaqueeee** [comment]
@2SI3NX much appreciated!

**Pull request merged**
