### PR TITLE
Update Ubuntu 16.04 x64 dependencies

### PR DESCRIPTION
**Pull request by amiuhle**
I needed this on Ubuntu 16.10 x64, so I'm guessing it'll be necessary on 16.04 also.

### CODE REVIEW

**Comment by amiuhle** [comment]
Is there something like `[skip-ci]` for changes like this?

**Comment by Jaqueeee** [comment]
Don't think there is a command to skip builds. @danrmiller might know?

**Comment by danrmiller** [comment]
> Is there something like [skip-ci] for changes like this?

@amiuhle I'm going to use a change_filter in buildbot for ignoring changes to files not related to the build. Do you use irc, and/or python, maybe I can run some things by you? I tried here for kovri but still have some testing to do: https://github.com/monero-project/meta/commit/c2c16bc890a7ea4737d8bb348d77a6d288508503

**Comment by amiuhle** [comment]
Yep, I'm on IRC, just let me know what I can do.

**Pull request merged**
