### PR TITLE
Custom password dialog. fixes issue with standard dialog

### PR DESCRIPTION
**Pull request by mbg033**
image
Fixes issue https://github.com/monero-project/monero-core/issues/86

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
Looks nice!

**Comment by M5M400** [comment]
looking good here!
screenshot from 2016-11-02 09-12-20

would be nice if one could just hit "enter" to confirm password though. Currently you have to confirm using the mouse to click the OK button.

**Comment by mbg033** [comment]
@M5M400 improved, now it accepted with Enter key, rejected with Esc. Also Tab changes the keyboard focus.

**Comment by taushet** [comment]
Works for me. No issues to report, other than that the OK/cancel buttons are in the wrong order by convention (the OK should be on the right)

**Comment by M5M400** [comment]
@mbg033 works for me as well, nice!

**Comment by medusadigital** [comment]
worked here

**Pull request merged**
