### PR TITLE
Update monero-core_de.ts

### PR DESCRIPTION
**Pull request by kaulkwappe**
Some improvements :)

### CODE REVIEW

**Comment by kaulkwappe** [comment]
Thanks! When does the file become updated so I can continue the translation?

**Comment by jonathancross** [comment]
@kaulkwappe It can take a while to be merged, just have to wait for @fluffypony.  He usually merges in batches every couple of weeks from what I've seen.

Did you have further German translations or for another language?
If you know how to use git on commandline, you can branch from this and add additional changes, then create a new Pull Request from that new branch.

**Comment by kaulkwappe** [comment]
Maybe I would continue the German translation so it becomes available in the stable :) I think Monero is a very interesting thing so I want to contribute a little bit.

**Comment by fluffypony** [comment]
@kaulkwappe congrats on your first merged pull request, and welcome to the Monero Project!

**Pull request merged**
