### PR TITLE
Wizard mobile redesign

### PR DESCRIPTION
**Pull request by Jaqueeee**
Redesign of wizard to make it look good on smaller screens.

### CODE REVIEW

**Comment by fluffypony** [comment]
Please rebase

**Comment by Jaqueeee** [comment]
rebased @fluffypony

**Comment by MoroccanMalinois** [comment]
Android screen shots for wizard pages : 
Before : 
screenshot_20170301-184215
screenshot_20170301-184222
screenshot_20170301-184236
screenshot_20170301-184243
screenshot_20170301-184302
screenshot_20170301-184309

With this PR : 

screenshot_20170301-182445
screenshot_20170301-182502
screenshot_20170301-182533
screenshot_20170301-182542
screenshot_20170301-182555
screenshot_20170301-182602

**Comment by Jaqueeee** [comment]
thanks for the screenshots @MoroccanMalinois! Is this on a tablet or a phone? Do you know what resolution you got on the device?

**Comment by MoroccanMalinois** [comment]
@Jaqueeee This is on a phone (SM-A510F) with 1920 x 1080 pixels.

**Pull request merged**
