### PR TITLE
Capitalize "Create tx file" button

### PR DESCRIPTION
**Pull request by xmr-eric**

### CODE REVIEW

**Comment by xmr-eric** [comment]
Please review my "updated translations" commit. The "Submodule monero updated 50 files" thing looks wonky to me.

**Comment by Jaqueeee** [comment]
Seems like you accident added the monero folder to your commit. Easiest way to remove it is resetting your lateat commit and create a new one without that folder.
`git reset HEAD~1`

**Comment by xmr-eric** [comment]
Alright I did it, but for some reason Atom editor deleted a bunch of extra spaces in the files that are on the ends of lines (not related to "Create tx file"). Will this mess up anything?

**Comment by xmr-eric** [comment]
Oops and now I see this commit "deleted submodule Monero". So I'm not sure if this should be merged.

**Comment by xmr-eric** [comment]
Alright I'm totally confused. I'm going to delete this commit and I'll submit a translation commit after this has been merged :)

**Pull request merged**
