### PR TITLE
Create view only wallet

### PR DESCRIPTION
**Pull request by Jaqueeee**
+ redesigned settings page

### CODE REVIEW

**Comment by xmr-eric** [comment]
Once I created the view wallet, it dropped me back into my current wallet, and I was immediately confused. For a second I thought the GUI had dropped me into the new view wallet. So I sent a test amount to prove I was in the real wallet.

Would it be possible to have a information "OK" box after the wallet is created? 

Perhaps the box could say, "The view only wallet has been created. You can open it by closing this current wallet, clicking the "Open wallet from file" option, and selecting the view wallet's .keys file."

Something like that. I also feel we should have a "Help" or "What is this?" info box next to the Create View Only Wallet button in Settings that describes how view wallets work and how the .keys files can be shared.

**Comment by fluffypony** [comment]
Please rebase

**Comment by Jaqueeee** [comment]
rebased and added success message @xmr-eric

**Comment by fluffypony** [comment]
Please rebase again

**Comment by Jaqueeee** [comment]
closing. Commits added to  #398 instead.

**Pull request closed without merging**
