### PR TITLE
Optional custom bar

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by xmr-eric** [comment]
On OSX 10.12.1

Wallet installs with custom title bar, which looks great. The question mark symbol doesn't seem to do anything (can we remove it?), but everything else works really well.

Unfortunately if you go into Settings and deselect "Custom decorations" the wallet should restore whatever title bar is default for the OS. But on OSX the title bar simply disappears completely, and theres no way to minimize the window or exit out of the program.

**Comment by xmr-eric** [comment]
@moneromooo-monero https://youtu.be/hoKH2ViAgdY

**Comment by moneromooo-monero** [comment]
I am unable to test this, as the WM I use is not running on the same VM as the GUI. I will try to fix this blind, but I will need someone to test for me.

**Comment by xmr-eric** [comment]
I can test

**Comment by moneromooo-monero** [comment]
Does https://github.com/moneromooo-monero/monero-core/tree/optional-custom-bar2 help ?

**Comment by moneromooo-monero** [comment]
If not, does https://github.com/moneromooo-monero/monero-core/tree/optional-custom-bar3 help ?

**Comment by fluffypony** [comment]
Plz rebase

**Comment by xmr-eric** [comment]
Still not working on my OSX 10.12.2 :\

**Comment by moneromooo-monero** [comment]
Are you running fullscreen ? medusa reports that it breaks when fullscreen on Mac.
If you can compile Qt, there's a sample called "windowflags" which you could try in the same settings to see if it also happens with it, or not.

**Pull request merged**
