### PR TITLE
First beta coming

### PR DESCRIPTION
**Pull request by mbg033**

### CODE REVIEW

**Comment by fluffypony** [comment]
Reviewed

**Comment by ChristopherKing42** [comment]
When will binaries come out?

**Comment by TommyEconomics** [comment]
Awesome work!

**Comment by NanoAkron** [comment]
95 commits! Woah...

**Comment by vergecurrency** [comment]
great job guys. i'm  excited to give it a spin!

**Comment by paulshapiro** [comment]
@NanoAkron that's gui dev for ya

**Pull request merged**
