### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by jonathancross**
This was copied over directly from #712 where @LvMsterfild had translated, but got stuck with git commands, revisions and squashing.

Only modifications were to revert nonsense translations like "Tip tekst test" that clearly are not real text and should not be "translated".

Note: I do not speak russian, but have reviewed these changes and done a sanity check using Google translate.

### CODE REVIEW

**Comment by LvMsterfild** [comment]
So,...Is it now everything is good ?

**Comment by jonathancross** [comment]
@LvMsterfild Please review the changes in "Files changed" tab for accuracy.
If they are good still, then you can click "Review changes" and then "Approve".

**Comment by jonathancross** [comment]
For project maintainers:
Here is a quick Google translate sanity check (side-by-side) comparison:
https://docs.google.com/spreadsheets/d/1s6o8PSGe0Gvaa6bEc5Ve4Md43GEKlIy3RrmkAhA34Io/edit#gid=0

It is easier to read because duplicate entries and html have been removed.

**Comment by LvMsterfild** [comment]
How about " type="unfinished" inside "translation" tag ? It must be
here necessarily
? What it means ? Will my translations display in GUI wallet if we leave it
?

2017-05-16 17:57 GMT+03:00 Jonathan Cross <notifications@github.com>:

**Comment by jonathancross** [comment]
Thanks @LvMsterfild
I corrected two cases of `type="unfinished"` where the translation was actually finished.
Please feel free to double click on any line to comment on that specific line of the file.

Thanks!

**Comment by jonathancross** [comment]
So, I built this RU version, but discovered that no russian seed phrase is being created... need to investigate.
Also have a few small missing translations (probably modified after the base translation file was created).

* Can anyone provide documentation / suggestions on the best way to handle these?
* Can we automatically update translation files with new strings that need to be translated?

**Comment by NanoAkron** [comment]
So this is probably because monero-core is slightly out of sync with the latest version of monero due to PR #2002 in monero.

All of the word lists are now known by their native names. This is solved by PR #692

**Comment by jonathancross** [comment]
Thanks @NanoAkron, that was the issue!
Should I create a separate PR to fix all languages?

Any suggestions on the second issue (extracting new strings that need to be translated)?

**Comment by jonathancross** [comment]
@LvMsterfild I've identified some additional translations needed, can you please provide these?
https://docs.google.com/spreadsheets/d/1s6o8PSGe0Gvaa6bEc5Ve4Md43GEKlIy3RrmkAhA34Io/edit#gid=1906641355

PS: There will probably be more in the future, but I think this should be good enough for now.

**Comment by LvMsterfild** [comment]
Of course. Can I edit this table ?
I finished ukrainian translation. Made the commit.
Also found my bugs in russian. I want to correct it

2017-05-17 2:49 GMT+03:00 Jonathan Cross <notifications@github.com>:

**Comment by NanoAkron** [comment]
@jonathancross Afraid I don't know how to solve the second issue. I have asked in the IRC channel if the PRs can be merged.

**Comment by jonathancross** [comment]
@LvMsterfild You now have edit access.

**Comment by jonathancross** [comment]
Thanks for providing the additional strings @LvMsterfild.
I'll add those in later once this PR and #736 are merged.

**Comment by fluffypony** [comment]
@jonathancross all yours - don't forget to rebase:)

**Comment by jonathancross** [comment]
Thanks @fluffypony, now rebased.
I'll add the additional RU translations in a separate PR so we can get this merged.

**Comment by jonathancross** [comment]
Thanks for the review @fluffypony

**Pull request merged**
