### PR TITLE
Cleanup. Remove bit from bitmonero.

### PR DESCRIPTION
**Pull request by codehalo**

### CODE REVIEW

**Comment by fluffypony** [comment]
Please rebase

**Comment by moneromooo-monero** [comment]
This includes commits by fluffypony and mbg033. Needs fixing. Typically, you run "git rebase master" from your branch after pulling on master.

**Comment by codehalo** [comment]
Thanks guys. I rebased. Can it this still not be merged?

**Comment by fluffypony** [comment]
The changes in 880e9aa14b9359e3f75ce77be78a80adeb5c74d1 and ba803dfb15a7bc04c4fe96dedbdede10f2927136 seem to already have been done by mbg033 - perhaps you weren't seeing it in your copy of the source?

**Comment by fluffypony** [comment]
There are some bits that he hasn't done, such as the whitespace cleanup at the end of get_libwallet_api.sh, but I'd suggest nuking your commits and doing it afresh :)

**Pull request closed without merging**
