### PR TITLE
Switch button position on password modal

### PR DESCRIPTION
**Pull request by taushet**
Buttons are the wrong way around (against convention)

Not tested.

### CODE REVIEW

**Comment by Jaqueeee** [comment]
Nice. But Ilya has implemented new password dialog recently https://github.com/monero-project/monero-core/pull/95

**Comment by taushet** [comment]
Sure, but the point stands.

**Comment by fluffypony** [comment]
You'll have to rebase it against the new dialog box

**Comment by taushet** [comment]
Done (I think...)

**Pull request closed without merging**
