### PR TITLE
Show password dialog before making a transfer

### PR DESCRIPTION
**Pull request by stoffu**

### CODE REVIEW

**Comment by stoffu** [comment]
@MaxXor 
Ouch! How embarrassing:) Thanks a lot for pointing it out, now fixed.

**Comment by medusadigital** [comment]
+next release

**Comment by medusadigital** [comment]
needs some more testing probably

**Comment by medusadigital** [comment]
@stoffu 

looking good to me. 

the only thing i found is:

if entering a password and pressing cancel on password promt next, password isnt reset. next time when trying to send, password will be there still. 

thats not a big issue for now, but if u have time please change it at some point.

**Pull request merged**
